///////////////////////////////////////////////////////////////////////////////
// TcAccessCoESdoViaAdsDrvInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcAccessCoESdoViaAdsDrvServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
