///////////////////////////////////////////////////////////////////////////////
// TcAccessCoESdoViaAdsDrvClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcAccessCoESdoViaAdsDrvClassFactory.h"
#include "TcAccessCoESdoViaAdsDrvServices.h"
#include "TcSdoAccessModul.h"

BEGIN_CLASS_MAP(CTcAccessCoESdoViaAdsDrvClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_TcAccessCoESdoViaAdsDrvCTcSdoAccessModul, SRVNAME_TCACCESSCOESDOVIAADSDRV "!CTcSdoAccessModul", CTcSdoAccessModul)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTcAccessCoESdoViaAdsDrvClassFactory::CTcAccessCoESdoViaAdsDrvClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TCACCESSCOESDOVIAADSDRV)); 
}

