///////////////////////////////////////////////////////////////////////////////
// TcAccessCoESdoViaAdsDrvServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcAccessCoESdoViaAdsDrv = 0x3F000000;
#define SRVNAME_TCACCESSCOESDOVIAADSDRV "TcAccessCoESdoViaAdsDrv"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TcAccessCoESdoViaAdsDrvCTcSdoAccessModul = {0x5ac9f19c,0x1f8e,0x4312,{0xaa,0xa1,0x35,0x29,0xbf,0x55,0x99,0xc1}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_TcSdoAccessModulDefaultAdsPort = 0x00000001;
const PTCID PID_TcSdoAccessModulCounter = 0x00000003;
const PTCID PID_TcSdoAccessModulVendorId = 0x00000004;
const PTCID PID_TcSdoAccessModulBaudRate = 0x00000006;
const PTCID PID_TcSdoAccessModulCoEVendorIdIndex = 0x00000005;
const PTCID PID_TcSdoAccessModulCoEVendorIdSubIndex = 0x00000007;
const PTCID PID_TcSdoAccessModulCoEBaudRateIndex = 0x00000008;
const PTCID PID_TcSdoAccessModulCoEBaudRateSubIndex = 0x00000009;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _TcSdoAccessModulInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
	AmsAddr AmsAddress;
} TcSdoAccessModulInputs, *PTcSdoAccessModulInputs;

typedef struct _TcSdoAccessModulOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} TcSdoAccessModulOutputs, *PTcSdoAccessModulOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
