///////////////////////////////////////////////////////////////////////////////
// ModuleDataInOut.h
#pragma once

#include "TcDataPointerSampleDrvInterfaces.h"

class CModuleDataInOut 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_TcDataPointerSampleDrvCModuleDataInOut)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleDataInOut();
	virtual	~CModuleDataInOut();

///<AutoGeneratedContent id="InterfaceMembers">
///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
	ModuleDataInOutInputSource m_InputSource;
	ModuleDataInOutOutputDestination m_OutputDestination;
///</AutoGeneratedContent>
};
