///////////////////////////////////////////////////////////////////////////////
// ModuleDataProvider.h
#pragma once

#include "TcDataPointerSampleDrvInterfaces.h"

class CModuleDataProvider 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcIoCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_TcDataPointerSampleDrvCModuleDataProvider)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleDataProvider();
	virtual	~CModuleDataProvider();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITcIoCyclic
	virtual HRESULT TCOMAPI InputUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, DWORD dwStateIn, ULONG_PTR context=0);
	virtual HRESULT TCOMAPI OutputUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, DWORD* pdwStateOut=0, ULONG_PTR context=0);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	ModuleDataProviderInput m_Input;
	ModuleDataProviderOutput m_Output;
	ModuleDataProviderData m_Data;
	ITcIoCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>
};
