///////////////////////////////////////////////////////////////////////////////
// ModuleDataAccessA.h
#pragma once

#include "TcDataPointerSampleDrvInterfaces.h"

class CModuleDataAccessA 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_TcDataPointerSampleDrvCModuleDataAccessA)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleDataAccessA();
	virtual	~CModuleDataAccessA();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	HRESULT InitDataPointer(); 
	VOID DeinitDataPointer();

///<AutoGeneratedContent id="Members">
	typedef _TCOM_SMARTDATAPTR<TInput> TInputDataPtr;
	typedef _TCOM_SMARTDATAPTR<TOutput> TOutputDataPtr;

	TcTraceLevel m_TraceLevelMax;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	TInputDataPtr m_spDataIn;
	TOutputDataPtr m_spDataOut;
///</AutoGeneratedContent>

	// Tracing
	CTcTrace m_Trace;

	// TODO: Custom variable
	UINT m_Counter;
};
