///////////////////////////////////////////////////////////////////////////////
// TcDataPointerSampleDrvServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcDataPointerSampleDrv = 0x3F000000;
#define SRVNAME_TCDATAPOINTERSAMPLEDRV "TcDataPointerSampleDrv"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TcDataPointerSampleDrvCModuleDataAccessA = {0xb9c9f2bf,0xd58c,0x44b1,{0xa8,0xfc,0xf1,0xa3,0x84,0x40,0x2d,0x68}};
const CTCID CID_TcDataPointerSampleDrvCModuleDataAccessB = {0x83aebf0a,0xba4f,0x4e0e,{0xae,0xc6,0x18,0xaa,0x58,0xad,0xeb,0x68}};
const CTCID CID_TcDataPointerSampleDrvCModuleDataProvider = {0xbb2eed4f,0x1afe,0x4c54,{0xab,0x85,0x82,0x59,0x66,0x58,0x76,0x6f}};
const CTCID CID_TcDataPointerSampleDrvCModuleDataInOut = {0x67d143d0,0xe160,0x45aa,{0xa3,0xa4,0xb0,0xb5,0x96,0xa9,0x4a,0x38}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleDataAccessADataIn = 0x00000002;
const PTCID PID_ModuleDataAccessADataOut = 0x00000003;
const PTCID PID_ModuleDataAccessBDataIn = 0x00000002;
const PTCID PID_ModuleDataAccessBDataOut = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_565F2CD7_9FA7_488E_81D6_20F1B6B05C62_INCLUDED_)
#define _TC_TYPE_565F2CD7_9FA7_488E_81D6_20F1B6B05C62_INCLUDED_
typedef struct _TInput
{
	ULONG ValueIn;
	unsigned char Bit1 : 1;
	unsigned char Bit2 : 1;
	unsigned char reserved1 : 6;
	unsigned char reserved2[3];
} TInput, *PTInput;
#endif // !defined(_TC_TYPE_565F2CD7_9FA7_488E_81D6_20F1B6B05C62_INCLUDED_)

#if !defined(_TC_TYPE_121813C3_D0DF_49E1_BA0D_BA8AA8ED3B63_INCLUDED_)
#define _TC_TYPE_121813C3_D0DF_49E1_BA0D_BA8AA8ED3B63_INCLUDED_
typedef struct _TOutput
{
	ULONG ValueOut;
	unsigned char BitOut1 : 1;
	unsigned char BitOut2 : 1;
	unsigned char reserved1 : 6;
	unsigned char reserved2[3];
} TOutput, *PTOutput;
#endif // !defined(_TC_TYPE_121813C3_D0DF_49E1_BA0D_BA8AA8ED3B63_INCLUDED_)

typedef struct _ModuleDataProviderInput
{
	TInput DataIn;
} ModuleDataProviderInput, *PModuleDataProviderInput;

typedef struct _ModuleDataProviderOutput
{
	TOutput DataOut;
} ModuleDataProviderOutput, *PModuleDataProviderOutput;

typedef struct _ModuleDataProviderData
{
	TInput DataIn;
	TOutput DataOut;
} ModuleDataProviderData, *PModuleDataProviderData;

typedef struct _ModuleDataInOutInputSource
{
	ULONG ValueIn;
	unsigned char Switch1 : 1;
	unsigned char Switch2 : 1;
	unsigned char reserved1 : 6;
	unsigned char reserved2[3];
} ModuleDataInOutInputSource, *PModuleDataInOutInputSource;

typedef struct _ModuleDataInOutOutputDestination
{
	ULONG ValueOut;
	unsigned char Lamp1 : 1;
	unsigned char Lamp2 : 1;
	unsigned char reserved1 : 6;
	unsigned char reserved2[3];
} ModuleDataInOutOutputDestination, *PModuleDataInOutOutputDestination;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
