///////////////////////////////////////////////////////////////////////////////
// TcDataPointerSampleDrvInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcDataPointerSampleDrvServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
