///////////////////////////////////////////////////////////////////////////////
// TcDataPointerSampleDrvClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcDataPointerSampleDrvClassFactory.h"
#include "TcDataPointerSampleDrvServices.h"
#include "ModuleDataAccessA.h"
#include "ModuleDataAccessB.h"
#include "ModuleDataProvider.h"
#include "ModuleDataInOut.h"

BEGIN_CLASS_MAP(CTcDataPointerSampleDrvClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_TcDataPointerSampleDrvCModuleDataAccessA, SRVNAME_TCDATAPOINTERSAMPLEDRV "!CModuleDataAccessA", CModuleDataAccessA)
	CLASS_ENTRY(CID_TcDataPointerSampleDrvCModuleDataAccessB, SRVNAME_TCDATAPOINTERSAMPLEDRV "!CModuleDataAccessB", CModuleDataAccessB)
	CLASS_ENTRY(CID_TcDataPointerSampleDrvCModuleDataProvider, SRVNAME_TCDATAPOINTERSAMPLEDRV "!CModuleDataProvider", CModuleDataProvider)
	CLASS_ENTRY(CID_TcDataPointerSampleDrvCModuleDataInOut, SRVNAME_TCDATAPOINTERSAMPLEDRV "!CModuleDataInOut", CModuleDataInOut)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTcDataPointerSampleDrvClassFactory::CTcDataPointerSampleDrvClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TCDATAPOINTERSAMPLEDRV)); 
}

