///////////////////////////////////////////////////////////////////////////////
// Untitled1ClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "Untitled1ClassFactory.h"
#include "Untitled1Services.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CUntitled1ClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_Untitled1CModule1, SRVNAME_UNTITLED1 "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CUntitled1ClassFactory::CUntitled1ClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_UNTITLED1)); 
}

