///////////////////////////////////////////////////////////////////////////////
// ModuleArchive.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ModuleArchive.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CModuleArchive
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CModuleArchive
BEGIN_INTERFACE_MAP(CModuleArchive)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_ITCOMOBJECT(CModuleArchive)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CModuleArchive)
IMPLEMENT_ITCADI(CModuleArchive)
IMPLEMENT_ITCWATCHSOURCE(CModuleArchive)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CModuleArchive 
BEGIN_SETOBJPARA_MAP(CModuleArchive)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_ModuleArchiveParameter, m_Parameter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CModuleArchive 
BEGIN_GETOBJPARA_MAP(CModuleArchive)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_ModuleArchiveParameter, m_Parameter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CModuleArchive
BEGIN_OBJPARAWATCH_MAP(CModuleArchive)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CModuleArchive
BEGIN_OBJDATAAREA_MAP(CModuleArchive)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(0, m_Inputs)
	OBJDATAAREA_VALUE(1, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CModuleArchive::CModuleArchive()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_counter(0)
{
	memset(&m_Parameter, 0, sizeof(m_Parameter)); 
	memset(&m_Inputs, 0, sizeof(m_Inputs)); 
	memset(&m_Outputs, 0, sizeof(m_Outputs)); 
}

///////////////////////////////////////////////////////////////////////////////
CModuleArchive::~CModuleArchive() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CModuleArchive)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CModuleArchive::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// Open archive and restore state
	ITComObjArchiveServerPtr spAS = m_spSrv;
	if (spAS == NULL)
	{
		m_Trace.Log(tlError, FNAMEA "TCom Object Archive Server not available"); 
	}
	else
	{
		// Create object archive for read, the archive resides in the TwinCAT boot directory in 
		// in subdirectory TcCom

		ITComArchiveOpPtr spAr; 
		if (FAILED(hr = spAS->CreateObjArchive(THIS_ITCOMOBJECT, TRUE, IID_ITComArchiveOp, (PPVOID)&spAr)))
		{
			if (hr == ADS_E_NOTFOUND)
			{
				m_Trace.Log(tlWarning, FNAMEA "CreateObjArchive returned file not found, using defaults (hr=0x%08x)", hr); 
				hr = S_OK;
			}
			else
			{
				// ADS_E_INCOMPATIBLE = file content incompatible
				// or other error codes
				m_Trace.Log(tlWarning, FNAMEA "CreateObjArchive failed (hr=0x%08x)", hr); 
			}
		}
		else
		{
			if (hr == S_OLDBOOTDATA)
			{
				m_Trace.Log(tlWarning, FNAMEA "CreateObjArchive found only old boot data"); 
			}
			hr = RestoreFromArchive(spAr); 
			if (FAILED(hr))
			{
				m_Trace.Log(tlError, FNAMEA "RestoreFromArchive failed (hr=0x%08x)", hr); 
			}
		}
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CModuleArchive::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization


	// If following call is successful the CycleUpdate method will be called, 
	// eventually even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CModuleArchive::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	// TODO: Add any additional deinitialization

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CModuleArchive::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// Store current state to archive
	ITComObjArchiveServerPtr spAS = m_spSrv;
	if (spAS == NULL)
	{
		m_Trace.Log(tlError, FNAMEA "TCom Object Archive Server not available"); 
	}
	else
	{
		// Create object archive for write, the archive resides in the TwinCAT boot directory in 
		// in subdirectory TcCom

		ITComArchiveOpPtr spAr; 
		if (FAILED(hr = spAS->CreateObjArchive(THIS_ITCOMOBJECT, FALSE, IID_ITComArchiveOp, (PPVOID)&spAr)))
		{
			m_Trace.Log(tlError, FNAMEA "CreateObjArchive failed (hr=0x%08x)", hr); 
		}
		else
		{
			hr = StoreToArchive(spAr); 
			if (FAILED(hr))
			{
				m_Trace.Log(tlError, FNAMEA "StoreToArchive failed (hr=0x%08x)", hr); 
			}
		}
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CModuleArchive::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// TODO: Replace the sample with your cyclic code
	m_counter++;
	m_Outputs.Value=m_counter;

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CModuleArchive::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CModuleArchive::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}


///////////////////////////////////////////////////////////////////////////////
HRESULT CModuleArchive::RestoreFromArchive(ITComArchiveOp* ipArchive)
{
	HRESULT hr = S_OK;
	if (ipArchive == NULL)
	{
		hr = E_POINTER;
	}
	else
	{
		*ipArchive >> m_counter;
		hr = ipArchive->GetResult();
	}
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
HRESULT CModuleArchive::StoreToArchive(ITComArchiveOp* ipArchive)
{
	HRESULT hr = S_OK;
	if (ipArchive == NULL)
	{
		hr = E_POINTER;
	}
	else
	{
		*ipArchive << m_counter;
		hr = ipArchive->GetResult();
	}
	return hr;
}

