///////////////////////////////////////////////////////////////////////////////
// ModuleArchive.h
#pragma once

#include "TcTComObjArchiveDrvInterfaces.h"

class CModuleArchive 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_TcTComObjArchiveDrvCModuleArchive)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleArchive();
	virtual	~CModuleArchive();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	HRESULT RestoreFromArchive(ITComArchiveOp* ipArchive);
	HRESULT StoreToArchive(ITComArchiveOp* ipArchive);
	HRESULT Serialize(ITComArchiveOp* ipArchive);

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	ModuleArchiveParameter m_Parameter;
	ModuleArchiveInputs m_Inputs;
	ModuleArchiveOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	// Tracing
	CTcTrace m_Trace;

	// TODO: Custom variable
	UINT m_counter;
};
