///////////////////////////////////////////////////////////////////////////////
// TcTComObjArchiveDrvServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcTComObjArchiveDrv = 0x3F000000;
#define SRVNAME_TCTCOMOBJARCHIVEDRV "TcTComObjArchiveDrv"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TcTComObjArchiveDrvCModuleArchive = {0x014eee8e,0xe957,0x4270,{0xa0,0xf8,0xa4,0x9e,0x60,0xc2,0xf8,0x7e}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleArchiveParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _ModuleArchiveParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} ModuleArchiveParameter, *PModuleArchiveParameter;

typedef struct _ModuleArchiveInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} ModuleArchiveInputs, *PModuleArchiveInputs;

typedef struct _ModuleArchiveOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} ModuleArchiveOutputs, *PModuleArchiveOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
