///////////////////////////////////////////////////////////////////////////////
// TcTComObjArchiveDrvClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcTComObjArchiveDrvClassFactory.h"
#include "TcTComObjArchiveDrvServices.h"
#include "ModuleArchive.h"

BEGIN_CLASS_MAP(CTcTComObjArchiveDrvClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_TcTComObjArchiveDrvCModuleArchive, SRVNAME_TCTCOMOBJARCHIVEDRV "!CModuleArchive", CModuleArchive)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTcTComObjArchiveDrvClassFactory::CTcTComObjArchiveDrvClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TCTCOMOBJARCHIVEDRV)); 
}

