///////////////////////////////////////////////////////////////////////////////
// SEHSampleClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "SEHSampleClassFactory.h"
#include "SEHSampleServices.h"
#include "SEHSampleVersion.h"
#include "SEHModule.h"

BEGIN_CLASS_MAP(CSEHSampleClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_SEHSampleCSEHModule, SRVNAME_SEHSAMPLE "!CSEHModule", CSEHModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CSEHSampleClassFactory::CSEHSampleClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_SEHSAMPLE)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(SEHSample));
#endif //defined(TCDBG_UNIT_VERSION)
}

