///////////////////////////////////////////////////////////////////////////////
// TcEthernetSampleInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcEthernetSampleServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_03010060_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_TYPE_03010060_0000_0000_E000_000000000064_INCLUDED_
struct __declspec(novtable) ITcEthernetAdapter : public ITcUnknown
{
	virtual HRESULT TCOMAPI RegisterProtocol(ITcIoEthProtocol* ipProt)=0;
	virtual HRESULT TCOMAPI UnregisterProtocol(ITcIoEthProtocol* ipProt)=0;
	virtual HRESULT TCOMAPI GetHwMacAddr(ETHERNET_ADDRESS* pMac)=0;
	virtual HRESULT TCOMAPI AddMulticastAddr(ETHERNET_ADDRESS mac)=0;
	virtual HRESULT TCOMAPI GetLinkError(BOOL* pbLinkError)=0;
	virtual HRESULT TCOMAPI GetLinkSpeed(ULONG* pSpeed)=0;
	virtual HRESULT TCOMAPI CheckRecvFrames(ITcIoEthProtocol* ipProt)=0;
	virtual HRESULT TCOMAPI SendFrame(TcEthernetAdapterPriority nPrio, PVOID pFrame, ULONG nFrame)=0;
	virtual HRESULT TCOMAPI ProcessSendFrames(PVOID ipTask, ULONG_PTR context)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcEthernetAdapter, IID_ITcEthernetAdapter);
#endif // !defined(_TC_TYPE_03010060_0000_0000_E000_000000000064_INCLUDED_)

#if !defined(_TC_TYPE_03010035_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_TYPE_03010035_0000_0000_E000_000000000064_INCLUDED_
struct __declspec(novtable) ITcIoEthProtocol : public ITcUnknown
{
	virtual HRESULT TCOMAPI CheckFrame(PVOID pData, ULONG nData, ULONG nVLanTag, ULONG nTimeStamp)=0;
	virtual HRESULT TCOMAPI LinkStatusChanged(BOOL bLinkError)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcIoEthProtocol, IID_ITcIoEthProtocol);
#endif // !defined(_TC_TYPE_03010035_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>
