///////////////////////////////////////////////////////////////////////////////
// DriverUsingStaticLibClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "DriverUsingStaticLibClassFactory.h"
#include "DriverUsingStaticLibServices.h"
#include "ModuleUsingStaticLib.h"

BEGIN_CLASS_MAP(CDriverUsingStaticLibClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_DriverUsingStaticLibCModuleUsingStaticLib, SRVNAME_DRIVERUSINGSTATICLIB "!CModuleUsingStaticLib", CModuleUsingStaticLib)
///</AutoGeneratedContent>
END_CLASS_MAP()

CDriverUsingStaticLibClassFactory::CDriverUsingStaticLibClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_DRIVERUSINGSTATICLIB)); 
}

