///////////////////////////////////////////////////////////////////////////////
// DriverUsingStaticLibInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "DriverUsingStaticLibServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
