///////////////////////////////////////////////////////////////////////////////
// DriverUsingStaticLibServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_DriverUsingStaticLib = 0x3F000000;
#define SRVNAME_DRIVERUSINGSTATICLIB "DriverUsingStaticLib"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_DriverUsingStaticLibCModuleUsingStaticLib = {0x443ad3a7,0x02be,0x478e,{0x96,0xff,0x00,0x20,0xd9,0xf1,0xe3,0x9f}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleUsingStaticLibParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _ModuleUsingStaticLibParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} ModuleUsingStaticLibParameter, *PModuleUsingStaticLibParameter;

typedef struct _ModuleUsingStaticLibInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
	ULONG Operand1;
	ULONG Operand2;
} ModuleUsingStaticLibInputs, *PModuleUsingStaticLibInputs;

typedef struct _ModuleUsingStaticLibOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
	ULONG CSResult;
	ULONG MResult;
} ModuleUsingStaticLibOutputs, *PModuleUsingStaticLibOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
