///////////////////////////////////////////////////////////////////////////////
// ModuleDPRAM.h
#pragma once

#include "TcPciIoDrvInterfaces.h"

class CModuleDPRAM 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_TcPciIoDrvCModuleDPRAM)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleDPRAM();
	virtual	~CModuleDPRAM();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	ModuleDPRAMParameter m_Parameter;
	ModuleDPRAMInputs m_Inputs;
	ModuleDPRAMOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	ITcADIPtr m_spPciDeviceAdi;
///</AutoGeneratedContent>

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	HRESULT AcquirePciDeviceAdi();
	VOID ReleasePciDeviceAdi();

	// Tracing
	CTcTrace m_Trace;

	// Custom variables
	PVOID m_pDataOut;
	PVOID m_pDataIn;
	UINT  m_counter;
};
