///////////////////////////////////////////////////////////////////////////////
// TcPciIoDrvClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcPciIoDrvClassFactory.h"
#include "TcPciIoDrvServices.h"
#include "ModuleDPRAM.h"

BEGIN_CLASS_MAP(CTcPciIoDrvClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_TcPciIoDrvCModuleDPRAM, SRVNAME_TCPCIIODRV "!CModuleDPRAM", CModuleDPRAM)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTcPciIoDrvClassFactory::CTcPciIoDrvClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TCPCIIODRV)); 
}

