///////////////////////////////////////////////////////////////////////////////
// StaticLibInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "StaticLibServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_6D2C52FF_48FF_4FAC_A000_482A66F82627_INCLUDED_)
#define _TC_TYPE_6D2C52FF_48FF_4FAC_A000_482A66F82627_INCLUDED_
struct __declspec(novtable) ISampleInterface : public ITcUnknown
{
	virtual HRESULT TCOMAPI SampleMultiplicationMethod(ULONG Parameter1, ULONG Parameter2, ULONG& Parameter3)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ISampleInterface, IID_ISampleInterface);
#endif // !defined(_TC_TYPE_6D2C52FF_48FF_4FAC_A000_482A66F82627_INCLUDED_)

///</AutoGeneratedContent>
