///////////////////////////////////////////////////////////////////////////////
// StaticLibServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_StaticLib = 0x3F000000;
#define SRVNAME_STATICLIB "StaticLib"

///<AutoGeneratedContent id="ClassIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
TCOM_DECL_INTERFACE("6d2c52ff-48ff-4fac-a000-482a66f82627", ISampleInterface)
///</AutoGeneratedContent>
