///////////////////////////////////////////////////////////////////////////////
// TcAsyncBufferWritingDrvInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcAsyncBufferWritingDrvServices.h"

// defining new interfaces provided by this driver
/* for example
struct __declspec(novtable) ITcAsyncBufferWritingDrvShortName : public ITcUnknown
{
	virtual ULONG TCOMAPI DoSomething(ULONG value1, UINT value2=0)=0;
	TCOMMETHOD(DoSomethingElse(PVOID ptr));
};
_TCOM_SMARTPTR_TYPEDEF(ITcAsyncBufferWritingDrvShortName, IID_ITcAsyncBufferWritingDrvShortName);
*/


///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
