///////////////////////////////////////////////////////////////////////////////
// TcAsyncBufferWritingModule.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcAsyncBufferWritingModule.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CTcAsyncBufferWritingModule
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CTcAsyncBufferWritingModule
BEGIN_INTERFACE_MAP(CTcAsyncBufferWritingModule)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_ITCOMOBJECT(CTcAsyncBufferWritingModule)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CTcAsyncBufferWritingModule)
IMPLEMENT_ITCADI(CTcAsyncBufferWritingModule)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CTcAsyncBufferWritingModule 
BEGIN_SETOBJPARA_MAP(CTcAsyncBufferWritingModule)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcAsyncBufferWritingModuleParameter, m_Parameter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CTcAsyncBufferWritingModule 
BEGIN_GETOBJPARA_MAP(CTcAsyncBufferWritingModule)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcAsyncBufferWritingModuleParameter, m_Parameter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CTcAsyncBufferWritingModule
BEGIN_OBJDATAAREA_MAP(CTcAsyncBufferWritingModule)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(0, m_Inputs)
	OBJDATAAREA_VALUE(1, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CTcAsyncBufferWritingModule::CTcAsyncBufferWritingModule()
	: m_counter(0)
{
	memset(&m_Parameter, 0, sizeof(m_Parameter)); 
	memset(&m_Inputs, 0, sizeof(m_Inputs)); 
	memset(&m_Outputs, 0, sizeof(m_Outputs)); 

	memset(&m_Buffer1, 0, sizeof(m_Buffer1));
	memset(&m_Buffer2, 0, sizeof(m_Buffer2));

	m_pBufferFill = m_Buffer1;
	m_nBufferFillIndex = 0;
	m_pBufferWrite = NULL;
}

///////////////////////////////////////////////////////////////////////////////
CTcAsyncBufferWritingModule::~CTcAsyncBufferWritingModule() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CTcAsyncBufferWritingModule)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CTcAsyncBufferWritingModule::SetObjStatePS(PTComInitDataHdr pInitData)
{
	HRESULT hr = S_OK;

	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);
	hr = m_spSrv->TcCreateInstance(CID_TcFileAccessAsync, m_spFileAccessAsync.GetIID(), (PPVOID)(&m_spFileAccessAsync)); 

	if (SUCCEEDED(hr))
	{
		ITComObjectPtr spFileAccessObj = m_spFileAccessAsync;

		OTCID oid = m_spCyclicCaller.GetOID();
		hr = FAILED(hr) ? hr : spFileAccessObj->TcSetObjPara(PID_TcFileAccessAsyncAdsProvider, sizeof(oid), &oid); 
		if (m_Parameter.SegmentSize == 0)
		{
			hr = ADS_E_INVALIDPARM; 
		}
		hr = FAILED(hr) ? hr : spFileAccessObj->TcSetObjPara(PID_TcFileAccessAsyncSegmentSize, sizeof(m_Parameter.SegmentSize), &m_Parameter.SegmentSize); 
		hr = FAILED(hr) ? hr : spFileAccessObj->TcSetObjPara(PID_TcFileAccessAsyncTimeoutMs, sizeof(m_Parameter.Timeout), &m_Parameter.Timeout); 
		hr = FAILED(hr) ? hr : spFileAccessObj->TcSetObjState(TCOM_STATE_SAFEOP, m_spSrv, NULL); 
	}

	TRACE(FTEXT("hr=0x%08x"), hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CTcAsyncBufferWritingModule::SetObjStateSO()
{
	HRESULT hr = S_OK;

	hr = AddModuleToCaller(); 

	// TODO: Add any additional initialization
	if (SUCCEEDED(hr))
	{
		ITComObjectPtr spFileAccessObj = m_spFileAccessAsync;
		hr = spFileAccessObj->TcSetObjState(TCOM_STATE_OP, m_spSrv, NULL); 
	}

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CTcAsyncBufferWritingModule::SetObjStateOS()
{
	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CTcAsyncBufferWritingModule::SetObjStateSP()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////
// ITcCyclic
///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CTcAsyncBufferWritingModule::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	if (FillBuffer(m_pBufferFill, ASYNCWRITE_BUFFERSIZE, m_nBufferFillIndex))
	{
		if (m_nBufferFillIndex == 0)
		{
			// this indicates that the buffer is full, switch to other buffer
			if (m_pBufferFill == m_Buffer1)
			{
				m_pBufferFill = m_Buffer2;
				m_pBufferWrite = m_Buffer1; 
			}
			else
			{
				m_pBufferFill = m_Buffer1;
				m_pBufferWrite = m_Buffer2;
			}
		}
	}

	if (!m_Inputs.DisableWrite)
	{
		if (m_pBufferWrite)
		{
			hr = 
				m_fsmFileWriter.Init
				(
					m_spSrv,
					m_spFileAccessAsync,
					"%TC_BOOTPRJPATH%AsyncTest.txt",
					reinterpret_cast<PBYTE>(m_pBufferWrite), 
					ASYNCWRITE_BUFFERSIZE*sizeof(float)
				); 
		}
		if (SUCCEEDED(hr))
		{
			m_pBufferWrite = NULL;
		}
	}

	if (m_fsmFileWriter.IsActive())
	{
		m_Outputs.WriteActive = TRUE;
		hr = m_fsmFileWriter.Eval();
		if (SUCCEEDED(hr))
		{
			m_Outputs.BytesWritten = m_fsmFileWriter.GetBytesWrittenTotal();
		}
	}
	else
	{
		m_Outputs.WriteActive = FALSE;
	}
	return hr;
}
///</AutoGeneratedContent>

BOOL CTcAsyncBufferWritingModule::FillBuffer
(
	float* pBuffer, 
	UINT nBuffer, 
	UINT& nBufferIndex
)
{
	m_counter++;

	if (nBufferIndex<nBuffer)
	{
		pBuffer[nBufferIndex] = static_cast<float>(m_counter);
		++nBufferIndex;
		if (nBufferIndex == nBuffer)
		{
			nBufferIndex = 0;
		}
		return TRUE;
	}
	else
	{
		return FALSE;
	}
}


///////////////////////////////////////////////////////////////////////////////
HRESULT CTcAsyncBufferWritingModule::AddModuleToCaller()
{
	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CTcAsyncBufferWritingModule::RemoveModuleFromCaller()
{
	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
}



