///////////////////////////////////////////////////////////////////////////////
// TcAsyncBufferWritingDrvServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcAsyncBufferWritingDrv = 0xF0000000;
#define SRVNAME_TCASYNCBUFFERWRITINGDRV "TcAsyncBufferWritingDrv"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TcAsyncBufferWritingDrvCTcAsyncBufferWritingModule = {0xfc81c8de,0xb8a7,0x4666,{0xb5,0x3d,0x33,0xe9,0x59,0x99,0x94,0xab}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_TcAsyncBufferWritingModuleParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _TcAsyncBufferWritingModuleParameter
{
	ULONG SegmentSize;
	ULONG Timeout;
} TcAsyncBufferWritingModuleParameter, *PTcAsyncBufferWritingModuleParameter;

typedef struct _TcAsyncBufferWritingModuleInputs
{
	bool DisableWrite;
} TcAsyncBufferWritingModuleInputs, *PTcAsyncBufferWritingModuleInputs;

typedef struct _TcAsyncBufferWritingModuleOutputs
{
	ULONG BytesWritten;
	bool WriteActive;
	unsigned char reserved1[3];
} TcAsyncBufferWritingModuleOutputs, *PTcAsyncBufferWritingModuleOutputs;

///</AutoGeneratedContent>
