///////////////////////////////////////////////////////////////////////////////
// TONInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "TONServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
