///////////////////////////////////////////////////////////////////////////////
// TONServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TON = 0x3F000000;
#define SRVNAME_TON "TON"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TONCModule1 = {0xd3dcb022,0x823f,0x463e,{0x99,0x3c,0x85,0xf6,0x1e,0x6e,0x34,0x6c}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	SHORT Value;
} Module1Outputs, *PModule1Outputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
