///////////////////////////////////////////////////////////////////////////////
// TcFileTestDrvClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcFileTestDrvClassFactory.h"
#include "TcFileTestDrvServices.h"
#include "TcFileTestDrv.h"

BEGIN_CLASS_MAP(CTcFileTestDrvClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_TcFileTestDrvCTcFileTestDrv, SRVNAME_TCFILETESTDRV "!CTcFileTestDrv", CTcFileTestDrv)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTcFileTestDrvClassFactory::CTcFileTestDrvClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TCFILETESTDRV)); 
}

