///////////////////////////////////////////////////////////////////////////////
// TcFileTestDrvServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcFileTestDrv = 0x3F000000;
#define SRVNAME_TCFILETESTDRV "TcFileTestDrv"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TcFileTestDrvCTcFileTestDrv = {0xdcf83596,0x249e,0x46f1,{0x92,0x3a,0xbd,0xf8,0xe6,0xbd,0x08,0x07}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_TcFileTestDrvParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _TcFileTestDrvParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} TcFileTestDrvParameter, *PTcFileTestDrvParameter;

typedef struct _TcFileTestDrvInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} TcFileTestDrvInputs, *PTcFileTestDrvInputs;

typedef struct _TcFileTestDrvOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} TcFileTestDrvOutputs, *PTcFileTestDrvOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
