// TcFileTestDrvW32.idl : IDL source for TcFileTestDrvW32.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (TcFileTestDrvW32.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(54EDF0AC-ACDE-4456-920E-A26D15A8503A),

		helpstring("ITcFileTestDrv Interface"),
		pointer_default(unique)
	]
	interface ITcFileTestDrvCtrl : IUnknown
	{
	};

[
	uuid(BF6DEC14-AD1A-44a6-82E2-5913CDE2288D),
	version(1.0),
	helpstring("TcFileTestDrvW32 1.0 Type Library")
]
library TCFILETESTDRVW32Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(F634CCE5-F3B1-47a9-8151-D2B004A4B8F3),
		helpstring("TcFileTestDrvCtrl Class")
	]
	coclass TcFileTestDrvCtrl
	{
		[default] interface ITcFileTestDrvCtrl;
	};
};
