///////////////////////////////////////////////////////////////////////////////
// TcFileTestDrvInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "TcFileTestDrvServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
