///////////////////////////////////////////////////////////////////////////////
// SortOrderServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_SortOrder = 0x3F000000;
#define SRVNAME_SORTORDER "SortOrder"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_SortOrderCSortOrderModule = {0x58adfa45,0x9d80,0x4e33,{0x9e,0x4a,0x8d,0x1e,0x8b,0x79,0xa1,0x2c}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _SortOrderModuleInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} SortOrderModuleInputs, *PSortOrderModuleInputs;

typedef struct _SortOrderModuleOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} SortOrderModuleOutputs, *PSortOrderModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_SortOrderModuleInputs 0
#define ADI_SortOrderModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
