///////////////////////////////////////////////////////////////////////////////
// ModuleDataProvider.h
#pragma once

#include "TcConcurrentDADrvInterfaces.h"
#include "TcRtInterfaces.h"

class CModuleDataProvider 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public IDataRead
	, public IDataWrite
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_TcConcurrentDADrvCModuleDataProvider)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleDataProvider();
	virtual	~CModuleDataProvider();

///<AutoGeneratedContent id="InterfaceMembers">
	// IDataRead
	virtual HRESULT TCOMAPI Retrieve(DataTypeCustom* pData);

	// IDataWrite
	virtual HRESULT TCOMAPI Store(DataTypeCustom* pData);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
	ModuleDataProviderProvided m_Provided;
///</AutoGeneratedContent>

	CCriticalSectionInstance m_csInstance;
};
