///////////////////////////////////////////////////////////////////////////////
// TcConcurrentDADrvServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcConcurrentDADrv = 0x3F000000;
#define SRVNAME_TCCONCURRENTDADRV "TcConcurrentDADrv"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TcConcurrentDADrvCModuleDataWrite = {0xbf391658,0xe866,0x4a44,{0x8a,0x82,0xe1,0x02,0x28,0x44,0xd1,0xda}};
const CTCID CID_TcConcurrentDADrvCModuleDataRead = {0x5068c489,0x9302,0x4fa6,{0xbf,0x4f,0xed,0x71,0x34,0x4d,0x94,0x46}};
const CTCID CID_TcConcurrentDADrvCModuleDataProvider = {0xab0ce45a,0xfbc0,0x42c7,{0x87,0x41,0xeb,0xbf,0xe4,0x1c,0x4f,0x24}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleDataWriteDataWriteCounterModulo = 0x00000006;
const PTCID PID_ModuleDataWriteDataWrite = 0x00000004;
const PTCID PID_ModuleDataReadDataReadCounterModulo = 0x00000005;
const PTCID PID_ModuleDataReadDataRead = 0x00000004;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_324F4ADD_1D49_4149_81B4_3EE35FD3EC51_INCLUDED_)
#define _TC_TYPE_324F4ADD_1D49_4149_81B4_3EE35FD3EC51_INCLUDED_
typedef struct _DataTypeCustom
{
	LONG Id;
	LONG Value1;
	LONG Value2;
	LONG Value3;
} DataTypeCustom, *PDataTypeCustom;
#endif // !defined(_TC_TYPE_324F4ADD_1D49_4149_81B4_3EE35FD3EC51_INCLUDED_)

typedef struct _ModuleDataWriteWrite
{
	DataTypeCustom Data;
} ModuleDataWriteWrite, *PModuleDataWriteWrite;

typedef struct _ModuleDataReadRead
{
	DataTypeCustom Data;
	ULONG MissedCount;
} ModuleDataReadRead, *PModuleDataReadRead;

typedef struct _ModuleDataProviderProvided
{
	DataTypeCustom Data;
	ULONG LastRead;
	ULONG LastWrite;
} ModuleDataProviderProvided, *PModuleDataProviderProvided;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
TCOM_DECL_INTERFACE("6663d11c-9744-493c-b1af-05e9c6c02c9f", IDataWrite)
TCOM_DECL_INTERFACE("2e73160f-c0f2-496e-a5ad-3578a6af14ef", IDataRead)
///</AutoGeneratedContent>
