///////////////////////////////////////////////////////////////////////////////
// TcConcurrentDADrvInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcConcurrentDADrvServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_6663D11C_9744_493C_B1AF_05E9C6C02C9F_INCLUDED_)
#define _TC_TYPE_6663D11C_9744_493C_B1AF_05E9C6C02C9F_INCLUDED_
struct __declspec(novtable) IDataWrite : public ITcUnknown
{
	virtual HRESULT TCOMAPI Store(DataTypeCustom* pData)=0;
};
_TCOM_SMARTPTR_TYPEDEF(IDataWrite, IID_IDataWrite);
#endif // !defined(_TC_TYPE_6663D11C_9744_493C_B1AF_05E9C6C02C9F_INCLUDED_)

#if !defined(_TC_TYPE_2E73160F_C0F2_496E_A5AD_3578A6AF14EF_INCLUDED_)
#define _TC_TYPE_2E73160F_C0F2_496E_A5AD_3578A6AF14EF_INCLUDED_
struct __declspec(novtable) IDataRead : public ITcUnknown
{
	virtual HRESULT TCOMAPI Retrieve(DataTypeCustom* pData)=0;
};
_TCOM_SMARTPTR_TYPEDEF(IDataRead, IID_IDataRead);
#endif // !defined(_TC_TYPE_2E73160F_C0F2_496E_A5AD_3578A6AF14EF_INCLUDED_)

///</AutoGeneratedContent>
