///////////////////////////////////////////////////////////////////////////////
// TcIoTaskImageAccessDrvInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcIoTaskImageAccessDrvServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
