///////////////////////////////////////////////////////////////////////////////
// TcIoTaskImageAccessDrvServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcIoTaskImageAccessDrv = 0x3F000000;
#define SRVNAME_TCIOTASKIMAGEACCESSDRV "TcIoTaskImageAccessDrv"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TcIoTaskImageAccessDrvCIoTaskImageAccessModule = {0x545521df,0x888c,0x4d86,{0xa1,0x0d,0x2f,0x1c,0xef,0x24,0x04,0x6a}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_IoTaskImageAccessModuleIoTaskImage = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
