///////////////////////////////////////////////////////////////////////////////
// Untitled1Interfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "Untitled1Services.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_FDA2E12E_D291_4178_9133_4BDA0AD5BF5C_INCLUDED_)
#define _TC_TYPE_FDA2E12E_D291_4178_9133_4BDA0AD5BF5C_INCLUDED_
struct __declspec(novtable) IRpcTest : public ITcUnknown
{
	virtual HRESULT TCOMAPI CallInWHResult(LONG in)=0;
	virtual HRESULT TCOMAPI CallIn(LONG in)=0;
};
_TCOM_SMARTPTR_TYPEDEF(IRpcTest, IID_IRpcTest);
#endif // !defined(_TC_TYPE_FDA2E12E_D291_4178_9133_4BDA0AD5BF5C_INCLUDED_)

#if !defined(_TC_TYPE_1988BCF1_52EE_48BA_ABA9_F2B8641FD5C1_INCLUDED_)
#define _TC_TYPE_1988BCF1_52EE_48BA_ABA9_F2B8641FD5C1_INCLUDED_
struct __declspec(novtable) IRpcTest2 : public ITcUnknown
{
	virtual HRESULT TCOMAPI AddWOHResult(LONG a, LONG b, LONG& sum)=0;
	virtual HRESULT TCOMAPI AddWHResult(LONG a, LONG b, LONG& sum)=0;
};
_TCOM_SMARTPTR_TYPEDEF(IRpcTest2, IID_IRpcTest2);
#endif // !defined(_TC_TYPE_1988BCF1_52EE_48BA_ABA9_F2B8641FD5C1_INCLUDED_)

///</AutoGeneratedContent>
