///////////////////////////////////////////////////////////////////////////////
// Untitled1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled1 = 0x3F000000;
#define SRVNAME_UNTITLED1 "Untitled1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled1CModule1 = {0x6ef61388,0x9d2d,0x410a,{0xa2,0xd3,0xbe,0x98,0x09,0xda,0x34,0xe3}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Parameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Module1Parameter, *PModule1Parameter;

typedef struct _Module1Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} Module1Outputs, *PModule1Outputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_FDA2E12E_D291_4178_9133_4BDA0AD5BF5C_INCLUDED_)
#define _TC_IID_FDA2E12E_D291_4178_9133_4BDA0AD5BF5C_INCLUDED_
TCOM_DECL_INTERFACE("fda2e12e-d291-4178-9133-4bda0ad5bf5c", IRpcTest)
#endif // !defined(_TC_IID_FDA2E12E_D291_4178_9133_4BDA0AD5BF5C_INCLUDED_)

#if !defined(_TC_IID_1988BCF1_52EE_48BA_ABA9_F2B8641FD5C1_INCLUDED_)
#define _TC_IID_1988BCF1_52EE_48BA_ABA9_F2B8641FD5C1_INCLUDED_
TCOM_DECL_INTERFACE("1988bcf1-52ee-48ba-aba9-f2b8641fd5c1", IRpcTest2)
#endif // !defined(_TC_IID_1988BCF1_52EE_48BA_ABA9_F2B8641FD5C1_INCLUDED_)

///</AutoGeneratedContent>
