///////////////////////////////////////////////////////////////////////////////
// InToOutServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_InToOut = 0x3F000000;
#define SRVNAME_INTOOUT "InToOut"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_InToOutCModuleInToOut = {0xd5f52841,0xf281,0x4452,{0xab,0x82,0x50,0xfd,0x93,0xe3,0x38,0x77}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleInToOutParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _ModuleInToOutParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} ModuleInToOutParameter, *PModuleInToOutParameter;

typedef struct _ModuleInToOutInputs
{
	ULONG Value;
} ModuleInToOutInputs, *PModuleInToOutInputs;

typedef struct _ModuleInToOutOutputs
{
	ULONG Value;
} ModuleInToOutOutputs, *PModuleInToOutOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
