///////////////////////////////////////////////////////////////////////////////
// InToOutClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "InToOutClassFactory.h"
#include "InToOutServices.h"
#include "ModuleInToOut.h"

BEGIN_CLASS_MAP(CInToOutClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_InToOutCModuleInToOut, SRVNAME_INTOOUT "!CModuleInToOut", CModuleInToOut)
///</AutoGeneratedContent>
END_CLASS_MAP()

CInToOutClassFactory::CInToOutClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_INTOOUT)); 
}

