///////////////////////////////////////////////////////////////////////////////
// TcStopWatchSampleClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcStopWatchSampleClassFactory.h"
#include "TcStopWatchSampleServices.h"
#include "StopWatchModule.h"

BEGIN_CLASS_MAP(CTcStopWatchSampleClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_TcStopWatchSampleCStopWatchModule, SRVNAME_TCSTOPWATCHSAMPLE "!CStopWatchModule", CStopWatchModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTcStopWatchSampleClassFactory::CTcStopWatchSampleClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TCSTOPWATCHSAMPLE)); 
}

