///////////////////////////////////////////////////////////////////////////////
// TcStopWatchSampleInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcStopWatchSampleServices.h"

// defining new interfaces provided by this driver
/* for example
struct __declspec(novtable) ITcStopWatchSampleShortName : public ITcUnknown
{
	virtual ULONG TCOMAPI DoSomething(ULONG value1, UINT value2=0)=0;
	TCOMMETHOD(DoSomethingElse(PVOID ptr));
};
_TCOM_SMARTPTR_TYPEDEF(ITcStopWatchSampleShortName, IID_ITcStopWatchSampleShortName);
*/


///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
