///////////////////////////////////////////////////////////////////////////////
// ReceiverInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ReceiverServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
