///////////////////////////////////////////////////////////////////////////////
// ReceiverServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Receiver = 0x3F000000;
#define SRVNAME_RECEIVER "Receiver"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ReceiverCModuleReceiver = {0x34ba8fcf,0xdff6,0x4135,{0xb8,0xc4,0x55,0x77,0x9b,0x35,0x99,0x30}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleReceiverDefaultAdsPort = 0x00000001;
const PTCID PID_ModuleReceiverCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_9390ED59_3A9A_4C35_B929_3DB46A97387C_INCLUDED_)
#define _TC_TYPE_9390ED59_3A9A_4C35_B929_3DB46A97387C_INCLUDED_
enum AdsNotificationStatus : SHORT {
	STATUS_INIT,
	STATUS_WAITHDL,
	STATUS_ADDNOT,
	STATUS_WAITADDNOT,
	STATUS_RECEIVINGNOT,
	STATUS_ERROR_ADDDEVNOT = 10,
	STATUS_ERROR_DEVNOT = 11,
	STATUS_ERROR_ADSCOM = 12
};
#endif // !defined(_TC_TYPE_9390ED59_3A9A_4C35_B929_3DB46A97387C_INCLUDED_)

typedef struct _ModuleReceiverInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} ModuleReceiverInputs, *PModuleReceiverInputs;

typedef struct _ModuleReceiverOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} ModuleReceiverOutputs, *PModuleReceiverOutputs;

#pragma pack(push,1)
typedef struct _ModuleReceiverAdsCommuncationDataArea
{
	LONG hUser;
	LONG hNotification;
	AdsNotificationStatus Status;
} ModuleReceiverAdsCommuncationDataArea, *PModuleReceiverAdsCommuncationDataArea;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
